added deployment and file group/permission changes for QC/Publish

diff --git a/Install b/Install
--- a/Install
+++ b/Install
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/sh -x
 
 #
 # Installation script
@@ -76,3 +76,69 @@ fi
 touch ${INPUTDIR}/temp.aes.txt
 touch  ${INPUTDIR}/temp.eae.txt
 touch  ${INPUTDIR}/temp.joined.txt
+
+#
+# For any server, if the input file
+# does not exist already, create one that is writable. This is just a
+# place holder until an input file is published. The input directory
+# should be opened up to allow the curation staff to publish new input
+# files.
+#
+if [ ! -f ${INPUT_FILE_DEFAULT} ]
+then
+    touch ${INPUT_FILE_DEFAULT}
+    chmod 664 ${INPUT_FILE_DEFAULT}
+    chgrp mgi ${INPUT_FILE_DEFAULT}
+fi
+
+chmod -f 775 ${INPUTDIR}
+chgrp mgi ${INPUTDIR}
+
+#
+# The DLAInstall script removes all permissions from shell scripts for
+# group "other" on non-development servers. The QC report wrapper
+# script needs to have permissions restored to allow the
+# curation staff to run it.
+#
+chmod -f 755 ${RNASEQLOAD_QC_SH}
+chmod -f 755 ${RNASEQLOAD_QC}
+
+# copy the scripts for curator use into a standard location which exists in
+# their path statements
+
+# trim any trailing slash from MGIBIN variable
+DEPLOY_PATH=`echo "${MGIBIN}" | sed 's./$..'`
+
+if [ "${DEPLOY_PATH}" = "" ]; then
+        echo "Warning: MGIBIN variable missing from mgiconfig; cannot deploy curator files"
+        exit 0
+fi
+
+if [ ! -d ${DEPLOY_PATH} ]; then
+        # failure to deploy is not a fatal error; could happen during
+        # development under a home directory
+        echo "Warning: ${DEPLOY_PATH} does not exist; curator scripts were not copied."
+        exit 0
+fi
+
+if [ -d ${DEPLOY_PATH} ]; then
+        # copy files, change permissions, and check for errors
+        # deployment errors are non-fatal, as they can occur regularly in an
+        # SE's development area
+
+        for file in runRnaseqQC publishRnaseq
+        do
+                cp bin/${file} ${DEPLOY_PATH}
+                if [ $? -ne 0 ]; then
+                        echo "Warning: Failed to copy ${file} to ${DEPLOY_PATH}"
+                fi
+
+                chmod 755 ${DEPLOY_PATH}/${file}
+                if [ $? -ne 0 ]; then
+                        echo "Warning: Failed to change permissions on ${DEPLOY_PATH}/${file}"
+                fi
+        done
+        echo "Deployed curator files to ${DEPLOY_PATH}"
+fi
+
+exit 0
